#!/bin/bash

set -euo pipefail
. /.functions
define_base_vars

usage()
{
	[ ${#} -eq 0 ] || err "${@}"
	echo -e "usage: ${0} [ -r | --replace ] [ -n namespace | --namespace namespace ] [ -p admin-password | --password admin-password ] application-name [ secret-contents-file | - ]"
	exit 1
}

ARGS="$(getopt -o "h?n:p:r" -l "help,replace,namespace:,password:" -n "${__SCRIPT}" -- "${@}")" || usage

REPLACE="false"
NAMESPACE_SET="false"
NAMESPACE=""
ADMIN_PASSWORD_SET="false"
ADMIN_PASSWORD=""

eval set -- "${ARGS}"
while true ; do
	case "${1}" in
		--help | -h | "-?" ) usage ;;

        --namespace | -n )
			as_boolean "${NAMESPACE_SET}" && fail "You may specify ${1} only once"
			NAMESPACE="${2}"
			is_valid_hostname_part "${NAMESPACE}" || fail "The namespace [${NAMESPACE}] is not valid (${1})"
			NAMESPACE_SET="true"
			shift 2
			;;

        --password | -p )
			as_boolean "${ADMIN_PASSWORD_SET}" && fail "You may specify ${1} only once"
			ADMIN_PASSWORD="${2}"
			[ -n "${ADMIN_PASSWORD}" ] || fail "The administrator password may not be the empty string"
			ADMIN_PASSWORD_SET="true"
			shift 2
			;;

		--replace | -r ) REPLACE="true" ; shift ;;

		-- ) shift ; break ;;
	esac
done

[ ${#} -ge 1 ] || usage
[ ${#} -le 2 ] || usage

APP="${1}"
[ -n "${APP}" ] || fail "The application name may not be an empty string"
is_valid_hostname_part "${APP}" || fail "The application name [${APP}] is not valid"

[ -n "${NAMESPACE}" ] || NAMESPACE="${POD_NAMESPACE:-"default"}"

[ ${#} -eq 2 ] && SECRET_CONTENTS=( "${2}" ) || SECRET_CONTENTS=()

as_boolean "${REPLACE}" && REPLACE_ARG=( --replace ) || REPLACE_ARG=()

set_or_default MNT_KV "kv"
set_or_default MNT_K8S "kubernetes"
set_or_default MNT_USERPASS "userpass"
set_or_default TOKEN_AUDIENCE "vault"

APP_NAME_PREFIX="${APP}@${NAMESPACE}"
APP_PATH="${NAMESPACE}/${APP}"
if [ "${NAMESPACE}" == "${APP}" ] ; then
	# Avoid "vault@vault", "verdaccio@verdaccio", "nexus@nexus", etc...
	APP_NAME_PREFIX="${APP}"
	APP_PATH="${APP}"
fi

POLICY_NAME="${NAMESPACE}.${APP}"
READ_POLICY="${POLICY_NAME}.read"
ADMIN_POLICY="${POLICY_NAME}.admin"

vault-set-policy "${REPLACE_ARG[@]}" "${READ_POLICY}" <<EOF
path "${MNT_KV}/+/${APP_PATH}" {
    capabilities = [ "list", "read" ]
}
EOF

#
# We use this to render the admin policy because
# the middle component shouldn't be rendered if
# NAMESPACE == APP
#
render_admin_policy()
{
	cat <<-EOF
	path "${MNT_KV}/metadata" {
	    capabilities = [ "list" ]
	}
	EOF
	if [ "${NAMESPACE}" != "${APP}" ] ; then
		cat <<-EOF
		path "${MNT_KV}/metadata/${NAMESPACE}" {
		    capabilities = [ "list" ]
		}
		EOF
	fi
	cat <<-EOF
	path "${MNT_KV}/+/${APP_PATH}" {
	    capabilities = [ "list", "read", "create", "update", "patch", "delete" ]
	}
	EOF
}

vault-set-policy "${REPLACE_ARG[@]}" "${ADMIN_POLICY}" < <(render_admin_policy) || exit ${?}

# Add the Kubernetes mapping to the service account
# that we'll use to create the auto-generated secret
READER_ROLE="${APP}.read"
[ "${APP}" != "${NAMESPACE}" ] && READER_ROLE="${NAMESPACE}.${READER_ROLE}"
ROLE_MAPPING_PATH="auth/${MNT_K8S}/role/${READER_ROLE}"
if as_boolean "${REPLACE}" || ! vault read "${ROLE_MAPPING_PATH}" &>/dev/null ; then
	SERVICE_ACCOUNT="${APP}-read"
	doing "Creating a role mapping for [${READER_ROLE}]..."
	CMD=(
		vault write "${ROLE_MAPPING_PATH}"
			alias_name_source=serviceaccount_name
			bound_service_account_names="${SERVICE_ACCOUNT}"
			bound_service_account_namespaces="${NAMESPACE}"
			token_ttl=0
			token_period=120
			audience="${TOKEN_AUDIENCE}"
	)
	OUT="$( "${CMD[@]}" 2>&1 )" || fail "Failed to create a role mapping for ${READER_ROLE} (rc=${?}):\n${OUT}"
	ok "Role mapping created!"
else
	ok "The role mapping for ${READER_ROLE} already exists!"
fi

# Create the admin user that will be used to populate
# the secret. Allow the admin password to be set
ADMIN_USER="${NAMESPACE}"
[ "${APP}" != "${NAMESPACE}" ] && ADMIN_USER+=".${APP}"
ADMIN_USER_PATH="auth/${MNT_USERPASS}/users/${ADMIN_USER}"
if as_boolean "${REPLACE}" || ! vault read "${ADMIN_USER_PATH}" &>/dev/null ; then
	doing "Creating an administrative user [${ADMIN_USER}]..."
	[ -n "${ADMIN_PASSWORD}" ] || ADMIN_PASSWORD="\$${ADMIN_USER}\$123\$"
	CMD=(
		vault write "${ADMIN_USER_PATH}"
			password="${ADMIN_PASSWORD}"
			policies="default,${READ_POLICY},${ADMIN_POLICY}"
	)
	OUT="$( "${CMD[@]}" 2>&1 )" || fail "Failed to create the administrative user [${ADMIN_USER}] (rc=${?}):\n${OUT}"
	ok "Administative user created!"
else
	ok "The administrative user ${ADMIN_USER} already exists!"
fi

#
# TODO: switch over to group-based access management?
#
# This might be cleaner in the long run because it allows us to create individual users
# for each person accessing the system while also allowing them access to different areas
#

vault-create-entity "${REPLACE_ARG[@]}" "${ADMIN_USER}" "${MNT_USERPASS}/${ADMIN_USER}" || exit ${?}
vault-create-entity "${REPLACE_ARG[@]}" "${READER_ROLE}" "${MNT_K8S}/${READER_ROLE}" || exit ${?}

GROUP_NAME="${APP}"
[ "${APP}" != "${NAMESPACE}" ] && GROUP_NAME="${NAMESPACE}/${GROUP_NAME}"
vault-create-group "${REPLACE_ARG[@]}" --policies "${ADMIN_POLICY}" "${GROUP_NAME}:admin" "entity/${ADMIN_USER}" || exit ${?}
vault-create-group "${REPLACE_ARG[@]}" --policies "${READ_POLICY}" "${GROUP_NAME}:read" "entity/${READER_ROLE}" "group/${GROUP_NAME}:admin" || exit ${?}

vault-create-kv-secret "${REPLACE_ARG[@]}" --mount "${MNT_KV}" "${APP_PATH}" "${SECRET_CONTENT[@]}" || exit ${?}

# All is well!
exit 0
