#!/bin/bash

set -euo pipefail
. /.functions
define_base_vars

. "${__BASEDIR}/.vault-common"

usage()
{
	[ ${#} -eq 0 ] || err "${@}"
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} [ -r | --replace ] [ -m mount | --mount mount ] secret-path [ secret-contents-file | - ] "
	exit 1
}

ARGS="$(getopt -o "h?rm:" -l "help,replace,mount:" -n "${__SCRIPT}" -- "${@}")" || usage

REPLACE="false"
MOUNT_SET="false"
MOUNT=""

eval set -- "${ARGS}"
while true ; do
	case "${1}" in
		--help | -h | "-?" ) usage ;;

		--mount | -m )
			as_boolean "${MOUNT_SET}" && fail "You may specify ${1} only once"
			MOUNT="${2}"
			[ -n "${MOUNT}" ] || fail "The mount point may not be the empty string"
			MOUNT_SET="true"
			shift 2
			;;

		--replace | -r ) REPLACE="true" ; shift ;;

		-- ) shift ; break ;;
	esac
done

[ ${#} -ge 1 ] || usage
[ ${#} -le 2 ] || usage

SECRET_PATH="${1}"
[ -n "${SECRET_PATH}" ] || fail "The secret path may not be an empty string"
[ -n "${MOUNT}" ] || MOUNT="kv"

set_vault_token || fail "Failed to compute the vault token with which to authenticate (rc=${?})"

SECRET_CONTENTS=""
if [ ${#} -eq 2 ] ; then
	SECRET_CONTENTS="${2}"
	if [ "${SECRET_CONTENTS}" == "-" ] ; then
		eyes "Capturing the secret's initial contents from STDIN ..."
		SECRET_CONTENTS="$(cat)" || fail "Failed to read the secret contents from STDIN (rc=${?})"
	else
		require_file_readable "${SECRET_CONTENTS}"
		eyes "Reading the secret's contents from [${SECRET_CONTENTS}] ..."
		SECRET_CONTENTS="$(<"${SECRET_CONTENTS}")"
	fi
fi

SECRET="/${MOUNT}/${SECRET_PATH}"
if ! as_boolean "${REPLACE}" && vault kv metadata get "${SECRET}" &>/dev/null ; then
	quit "The secret [${SECRET}] is already populated!"
fi

VALUES=()
doing "Populating the secret at [${SECRET}] with these values:"
while read LINE ; do
	[ -n "${LINE}" ] || continue
	[[ "${LINE}" =~ ^([^=[:space:]]+)[[:space:]]*=(.*)$ ]] || continue
	KEY="${BASH_REMATCH[1]}"
	VALUE="${BASH_REMATCH[2]}"
	HASH="$(echo -n "${VALUE}" | sha256sum | awk '{ print $1 }')"
	VALUES+=( "${KEY}=${VALUE}" )
	echo -e "\t${KEY}=(sha256:${HASH})"
done < <(echo "${SECRET_CONTENTS}" | sed -e 's;#.*$;;g' -e '/^\s*$/d' | grep '=' | sort)

# Add a default value if none was given
if [ "${#VALUES[@]}" -eq 0 ] ; then
	KEY="placeholder"
	VALUE="ignore-or-delete-me"
	HASH="$(echo -n "${VALUE}" | sha256sum | awk '{ print $1 }')"
	VALUES+=( "${KEY}=${VALUE}" )
	echo -e "\t${KEY}=(sha256:${HASH})"
fi
OUT="$(vault kv put "${SECRET}" "${VALUES[@]}" 2>&1)" || fail "Failed to create the secret at [${SECRET}] (rc=${?}):\n${OUT}"
ok "Secret populated with ${#VALUES[@]} value(s)!"
exit 0
