#!/bin/bash

set -euo pipefail
. /.functions
define_base_vars

. "${__BASEDIR}/.vault-common"

usage()
{
	[ ${#} -eq 0 ] || err "${@}"
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} policy-name"
	exit 1
}

ARGS="$(getopt -o "h?" -l "help" -n "${__SCRIPT}" -- "${@}")" || usage

eval set -- "${ARGS}"
while true ; do
	case "${1}" in
		--help | -h | "-?" ) usage ;;

		-- ) shift ; break ;;
	esac
done

[ ${#} -eq 1 ] || usage

POLICY_NAME="${1}"
[ -n "${POLICY_NAME}" ] || fail "The policy name may not be an empty string"

set_vault_token || fail "Failed to compute the vault token with which to authenticate (rc=${?})"

vault policy read "${POLICY_NAME}" &>/dev/null || exit 0
warn "Deleting the policy [${POLICY_NAME}]..."
OUT="$(vault policy delete "${POLICY_NAME}" 2>&1)" || fail "Failed to delete the policy [${POLICY_NAME}] (rc=${?}):\n${OUT}"
ok "Deleted!"
exit 0
