#!/bin/bash

set -euo pipefail
. /.functions
define_base_vars

. "${__BASEDIR}/.vault-common"

usage()
{
	[ ${#} -eq 0 ] || err "${@}"
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} entity-name"
	exit 1
}

ARGS="$(getopt -o "h?" -l "help" -n "${__SCRIPT}" -- "${@}")" || usage

eval set -- "${ARGS}"
while true ; do
	case "${1}" in
		--help | -h | "-?" ) usage ;;

		-- ) shift ; break ;;
	esac
done

[ ${#} -eq 1 ] || usage

ENTITY="${1}"
[ -n "${ENTITY}" ] || fail "The entity name may not be an empty string"
shift

set_vault_token || fail "Failed to compute the vault token with which to authenticate (rc=${?})"

ENTITY_PATH="identity/entity/name/${ENTITY}"
vault read "${ENTITY_PATH}" &>/dev/null || exit 0
OUT="$(vault delete "${ENTITY_PATH}" 2>&1)" || fail "Failed to delete the entity [${ENTITY}] (rc=${?}:\n${OUT}"
ok "Deleted the entity [${ENTITY}]!"
exit 0
