#!/bin/bash

set -euo pipefail
. /.functions
define_base_vars

. "${__BASEDIR}/.vault-common"

list_namespaces()
{
	local JSON="$(cat)"
	(
		# Can't use this yet b/c this is a JSON/YAML selector spec, which means it's
		# not straightforward to transpose that to a kubectl CLI --selector call
		# SELECTOR="$(jq -r '.data.bound_service_account_namespace_selector' <<< "${JSON}")"
		SELECTOR=""
		if [ -n "${SELECTOR}" ] && type -P kubectl &>/dev/null ; then
			kubectl get namespace --no-headers --output custom-columns="NAME:.metadata.name" --selector "${SELECTOR}"
		fi
		jq -r '.data.bound_service_account_namespaces[]' <<< "${JSON}"
	) | sort -u
}

usage()
{
	[ ${#} -eq 0 ] || err "${@}"
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} [ -r | --replace ] entity-name [ alias-1 alias-2 ... alias-N ]"
	exit 1
}

ARGS="$(getopt -o "h?r" -l "help,replace" -n "${__SCRIPT}" -- "${@}")" || usage

REPLACE="false"

eval set -- "${ARGS}"
while true ; do
	case "${1}" in
		--help | -h | "-?" ) usage ;;

		--replace | -r ) REPLACE="true" ; shift ;;

		-- ) shift ; break ;;
	esac
done

[ ${#} -ge 1 ] || usage

ENTITY="${1}"
[ -n "${ENTITY}" ] || fail "The entity name may not be an empty string"
shift

set_vault_token || fail "Failed to compute the vault token with which to authenticate (rc=${?})"

ENTITY_JSON="$(vault read -format=json "/identity/entity/name/${ENTITY}" 2>&1)" && EXISTS="true" || EXISTS="false"
if as_boolean "${REPLACE}" || ! as_boolean "${EXISTS}" ; then
	if as_boolean "${EXISTS}" ; then
		warn "Deleting the existing entity [${ENTITY}]..."
		OUT="$(vault delete "/identity/entity/name/${ENTITY}" 2>&1)" || warn "Failed to delete the existing entity [${ENTITY}] (rc=${?}:\n${OUT}"
		ok "Existing entity deleted!"
	fi

	doing "Creating a new entity named [${ENTITY}] ..."
	ENTITY_JSON="$(vault write -format=json identity/entity name="${ENTITY}" 2>&1)" || fail "Failed to create the entity [${ENTITY}] (rc=${?}):\n${ENTITY_JSON}"
	ok "Entity created!"
else
	ok "The entity [${ENTITY}] already exists!"
fi

# If there are no aliases to map to, we simply don't
[ ${#} -gt 0 ] || exit 0

# Aliases must be in the format authpath/name, since this is how we'll identify its accessor ID

ENTITY_ID="$(jq -r '.data.id // ""' <<< "${ENTITY_JSON}" 2>&1)" || fail "Can't add aliases! Failed to harvest the entity ID from the JSON output (rc=${?}):\n${ENTITY_ID}\n\n${ENTITY_JSON}"

AUTH_LIST="$(vault auth list -format=json 2>&1)" || fail "Failed to get the authentication list from Vault (rc=${?}): ${AUTH_LIST}"

for ALIAS in "${@}" ; do
	[[ "${ALIAS}" =~ ^([^/]+/)([^/]+)$ ]] || fail "Invalid alias [${ALIAS}] - must be in the form auth-path/target-name"
	ACCESSOR="${BASH_REMATCH[1]}"
	TARGET_NAME="${BASH_REMATCH[2]}"

	ACCESSOR_JSON="$(jq -r --arg K "${ACCESSOR}" '.[$K] // {}' <<< "${AUTH_LIST}" 2>&1)" || fail "Failed to find the accessor for [${ALIAS}] (rc=${?}): ${ACCESSOR_JSON}"
	ACCESSOR_TYPE="$(jq -r '.type // ""' <<< "${ACCESSOR_JSON}" 2>&1)" || fail "Failed to read the accessor type for [${ALIAS}] (rc=${?}): ${ACCESSOR_TYPE}"
	[ -n "${ACCESSOR_TYPE}" ] || fail "Invalid acecssor [${ACCESSOR}] from alias [${ALIAS}] - no type found!"

	ACCESSOR_ID="$(jq -r '.accessor // ""' <<< "${ACCESSOR_JSON}" 2>&1)" || fail "Failed to find the accessor ID for [${ALIAS}] (rc=${?}): ${ACCESSOR_ID}"
	[ -n "${ACCESSOR_ID}" ] || fail "Invalid accessor [${ACCESSOR}] from alias [${ALIAS}] - no ID found!"

	# Default value...
	TARGETS=( "${TARGET_NAME}" )

	case "${ACCESSOR_TYPE}" in
		# For kubernetes we must also also pre-pend the namespace to the target name
		"kubernetes" )
			TARGET_JSON="$(vault read -format=json "auth/${ACCESSOR}role/${TARGET_NAME}" 2>&1)" || fail "Failed to read the Kubernetes role [${TARGET_NAME}] from the accessor [${ACCESSOR}] (rc=${?}):\n${TARGET_JSON}"
			TARGETS=()
			while read NAMESPACE ; do
				TARGETS+=( "${NAMESPACE}/${TARGET_NAME}" )
			done < <(list_namespaces <<< "${TARGET_JSON}")
			;;

		# Other special cases?
	esac

	if [ ${#TARGETS[@]} -eq 0 ] ; then
		warn "No valid targets found for the alias [${ALIAS}] for [${ENTITY}]"
		continue
	fi

	for TARGET in "${TARGETS[@]}" ; do
		doing "Creating an entity alias for [${TARGET}] as [${ENTITY}] (from [${ALIAS}])"
		CMD=(
			vault write identity/entity-alias
				name="${TARGET}"
				canonical_id="${ENTITY_ID}"
				mount_accessor="${ACCESSOR_ID}"
		)
		OUT="$( "${CMD[@]}" 2>&1 )" || fail "Failed to create the entity alias on [${ENTITY}] for the target [${TARGET}] (rc=${?}):\n${OUT}"
	done
	ok "Alias [${ALIAS}] created on entity [${ENTITY}]!"
done
exit 0
