#!/bin/bash

set -euo pipefail
. /.functions
define_base_vars

. "${__BASEDIR}/.vault-common"

usage()
{
	[ ${#} -eq 0 ] || err "${@}"
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} [ -m mount | --mount mount ] secret-path"
	exit 1
}

ARGS="$(getopt -o "h?m:" -l "help,mount:" -n "${__SCRIPT}" -- "${@}")" || usage

MOUNT_SET="false"
MOUNT=""

eval set -- "${ARGS}"
while true ; do
	case "${1}" in
		--help | -h | "-?" ) usage ;;

		--mount | -m )
			as_boolean "${MOUNT_SET}" && fail "You may specify ${1} only once"
			MOUNT="${2}"
			[ -n "${MOUNT}" ] || fail "The mount point may not be the empty string"
			MOUNT_SET="true"
			shift 2
			;;

		-- ) shift ; break ;;
	esac
done

[ ${#} -eq 1 ] || usage

SECRET="${1}"
[ -n "${SECRET}" ] || fail "The secret path may not be an empty string"
[ -n "${MOUNT}" ] || MOUNT="${MNT_KV:-"kv"}"

set_vault_token || fail "Failed to compute the vault token with which to authenticate (rc=${?})"

vault kv metadata get -mount="${MOUNT}" "${SECRET}" &>/dev/null || exit 0
warn "Deleting the KV secret at [/${MOUNT}/${SECRET}] ..."
OUT="$(vault kv metadata delete -mount="${MOUNT}" "${SECRET}" 2>&1)" || fail "Failed to delete the KV secret at [/${MOUNT}/${SECRET}] (rc=${?}):\n${OUT}"
ok "Deleted!"
exit 0
