#!/bin/bash

set -euo pipefail
. /.functions
define_base_vars

. "${__BASEDIR}/.vault-common"

usage()
{
	[ ${#} -eq 0 ] || err "${@}"
	echo -e "usage: ${0} [ -s | --secret ] [ -n namespace | --namespace namespace ] application-name"
	exit 1
}

ARGS="$(getopt -o "h?n:p:r" -l "help,secret,namespace:" -n "${__SCRIPT}" -- "${@}")" || usage

SECRET="false"
NAMESPACE_SET="false"
NAMESPACE=""

eval set -- "${ARGS}"
while true ; do
	case "${1}" in
		--help | -h | "-?" ) usage ;;

	    --namespace | -n )
			as_boolean "${NAMESPACE_SET}" && fail "You may specify ${1} only once"
			NAMESPACE="${2}"
			is_valid_hostname_part "${NAMESPACE}" || fail "The namespace [${NAMESPACE}] is not valid (${1})"
			NAMESPACE_SET="true"
			shift 2
			;;

		--secret | -s ) SECRET="true" ; shift ;;

		-- ) shift ; break ;;
	esac
done

[ ${#} -eq 1 ] || usage

APP="${1}"
[ -n "${APP}" ] || fail "The application name may not be an empty string"
is_valid_hostname_part "${APP}" || fail "The application name [${APP}] is not valid"

set_vault_token || fail "Failed to compute the vault token with which to authenticate (rc=${?})"

[ -n "${NAMESPACE}" ] || NAMESPACE="${POD_NAMESPACE:-"default"}"

ADMIN_USER="${APP}"
APP_PATH="${APP}"
GROUP_NAME="${APP}"
POLICY_NAME="${APP}"
ROLE_NAME="${APP}"
# Avoid "vault@vault", "verdaccio@verdaccio", "nexus@nexus", etc...
if [ "${NAMESPACE}" != "${APP}" ] ; then
	ADMIN_USER="${NAMESPACE}.${ADMIN_USER}"
	APP_PATH="${NAMESPACE}/${APP_PATH}"
	GROUP_NAME="${NAMESPACE}/${GROUP_NAME}"
	POLICY_NAME="${NAMESPACE}.${POLICY_NAME}"
	ROLE_NAME="${NAMESPACE}.${ROLE_NAME}"
fi

FAILED="false"

vault-delete-policy "${POLICY_NAME}.read" || FAILED="true"
vault-delete-policy "${POLICY_NAME}.admin" || FAILED="true"

vault-delete-user "${ADMIN_USER}" || FAILED="true"
vault-delete-entity "${ADMIN_USER}" || FAILED="true"

ADMIN_ROLE="${ROLE_NAME}.admin"
vault-delete-group "${GROUP_NAME}:admin" || FAILED="true"
vault-delete-entity "${ADMIN_ROLE}" || FAILED="true"
vault-delete-k8s-role "${ADMIN_ROLE}" || FAILED="true"

READER_ROLE="${ROLE_NAME}.read"
vault-delete-group "${GROUP_NAME}:read" || FAILED="true"
vault-delete-entity "${READER_ROLE}" || FAILED="true"
vault-delete-k8s-role "${READER_ROLE}" || FAILED="true"

if as_boolean "${SECRET}" ; then
	vault-delete-kv-secret "${APP_PATH}" || FAILED="true"
fi

as_boolean "${FAILED}" && exit 1
exit 0
