#!/bin/bash

set -euo pipefail
. /.functions
define_base_vars

. "${__BASEDIR}/.vault-common"

usage()
{
	[ ${#} -eq 0 ] || err "${@}"
	echo -e "usage: ${BASH_ARGV0:-${BASH_SOURCE:-${0}}} role"
	exit 1
}

ARGS="$(getopt -o "h?r" -l "help" -n "${__SCRIPT}" -- "${@}")" || usage

eval set -- "${ARGS}"
while true ; do
	case "${1}" in
		--help | -h | "-?" ) usage ;;

		-- ) shift ; break ;;
	esac
done

[ ${#} -eq 1 ] || usage

ROLE="${1}"
[ -n "${ROLE}" ] || fail "The role name may not be an empty string"
shift

set_vault_token || fail "Failed to compute the vault token with which to authenticate (rc=${?})"

ROLE_PATH="/auth/${MNT_K8S}/role/${ROLE}"
vault read "${ROLE_PATH}" &>/dev/null || exit 0
warn "Deleting the role [${ROLE}] ..."
OUT="$(vault delete "${ROLE_PATH}" 2>&1)" || fail "Failed to delete the role [${ROLE}] (rc=${?}):\n${OUT}"
ok "Deleted!"
exit 0
