#!/bin/bash

set -euo pipefail
. /.functions
define_base_vars

. "${__BASEDIR}/.vault-common"

usage()
{
	[ ${#} -eq 0 ] || err "${@}"
	echo -e "usage: ${0} [ -r | --replace ] [ -n namespace | --namespace namespace ] [ -p admin-password | --password admin-password ] application-name [ secret-contents-file | - ]"
	exit 1
}

ARGS="$(getopt -o "h?n:p:r" -l "help,replace,namespace:,password:" -n "${__SCRIPT}" -- "${@}")" || usage

REPLACE="false"
NAMESPACE_SET="false"
NAMESPACE=""
ADMIN_PASSWORD_SET="false"
ADMIN_PASSWORD=""

eval set -- "${ARGS}"
while true ; do
	case "${1}" in
		--help | -h | "-?" ) usage ;;

        --namespace | -n )
			as_boolean "${NAMESPACE_SET}" && fail "You may specify ${1} only once"
			NAMESPACE="${2}"
			is_valid_hostname_part "${NAMESPACE}" || fail "The namespace [${NAMESPACE}] is not valid (${1})"
			NAMESPACE_SET="true"
			shift 2
			;;

        --password | -p )
			as_boolean "${ADMIN_PASSWORD_SET}" && fail "You may specify ${1} only once"
			ADMIN_PASSWORD="${2}"
			[ -n "${ADMIN_PASSWORD}" ] || fail "The administrator password may not be the empty string"
			ADMIN_PASSWORD_SET="true"
			shift 2
			;;

		--replace | -r ) REPLACE="true" ; shift ;;

		-- ) shift ; break ;;
	esac
done

[ ${#} -ge 1 ] || usage
[ ${#} -le 2 ] || usage

APP="${1}"
[ -n "${APP}" ] || fail "The application name may not be an empty string"
is_valid_hostname_part "${APP}" || fail "The application name [${APP}] is not valid"

set_vault_token || fail "Failed to compute the vault token with which to authenticate (rc=${?})"

[ -n "${NAMESPACE}" ] || NAMESPACE="${POD_NAMESPACE:-"default"}"

[ ${#} -eq 2 ] && SECRET_CONTENTS=( "${2}" ) || SECRET_CONTENTS=()

as_boolean "${REPLACE}" && REPLACE_ARG=( --replace ) || REPLACE_ARG=()

ADMIN_USER="${APP}"
APP_PATH="${APP}"
GROUP_NAME="${APP}"
POLICY_NAME="${APP}"
ROLE_NAME="${APP}"
# Avoid "vault@vault", "verdaccio@verdaccio", "nexus@nexus", etc...
if [ "${NAMESPACE}" != "${APP}" ] ; then
	ADMIN_USER="${NAMESPACE}.${ADMIN_USER}"
	APP_PATH="${NAMESPACE}/${APP_PATH}"
	GROUP_NAME="${NAMESPACE}/${GROUP_NAME}"
	POLICY_NAME="${NAMESPACE}.${POLICY_NAME}"
	ROLE_NAME="${NAMESPACE}.${ROLE_NAME}"
fi

READ_POLICY="${POLICY_NAME}.read"
vault-create-policy "${REPLACE_ARG[@]}" "${READ_POLICY}" <<EOF
path "${MNT_KV}/+/${APP_PATH}" {
    capabilities = [ "list", "read" ]
}
EOF

#
# We use this to render the admin policy because
# the middle component shouldn't be rendered if
# NAMESPACE == APP
#
render_admin_policy()
{
	cat <<-EOF
	path "${MNT_KV}/metadata" {
	    capabilities = [ "list" ]
	}
	EOF
	if [ "${NAMESPACE}" != "${APP}" ] ; then
		cat <<-EOF
		path "${MNT_KV}/metadata/${NAMESPACE}" {
		    capabilities = [ "list" ]
		}
		EOF
	fi
	cat <<-EOF
	path "${MNT_KV}/+/${APP_PATH}" {
	    capabilities = [ "list", "read", "create", "update", "patch", "delete" ]
	}
	EOF
}

ADMIN_POLICY="${POLICY_NAME}.admin"
vault-create-policy "${REPLACE_ARG[@]}" "${ADMIN_POLICY}" < <(render_admin_policy) || exit ${?}

SERVICE_ACCOUNT="vault-${APP}"

#
# This is used for secret administration
#
as_boolean "${ADMIN_PASSWORD_SET}" && PASSWORD_ARG=( --password "${PASSWORD}" ) || PASSWORD_ARG=()
vault-create-user "${REPLACE_ARG[@]}" "${PASSWORD_ARG[@]}" "${ADMIN_USER}" || exit ${?}
vault-create-entity "${REPLACE_ARG[@]}" "${ADMIN_USER}" "${MNT_USERPASS}/${ADMIN_USER}" || exit ${?}

ADMIN_SERVICE_ACCOUNT="${SERVICE_ACCOUNT}-admin"
ADMIN_ROLE="${ROLE_NAME}.admin"
vault-create-k8s-role "${REPLACE_ARG[@]}" "${ADMIN_ROLE}" "${NAMESPACE}/${ADMIN_SERVICE_ACCOUNT}" || exit ${?}
vault-create-entity "${REPLACE_ARG[@]}" "${ADMIN_ROLE}" "${MNT_K8S}/${ADMIN_ROLE}" || exit ${?}

ADMIN_GROUP="${GROUP_NAME}:admin"
vault-create-group "${REPLACE_ARG[@]}" --policies "${ADMIN_POLICY}" "${ADMIN_GROUP}" "entity/${ADMIN_USER}" "entity/${ADMIN_ROLE}" || exit ${?}

#
# This is used just for reading the secret
#
READ_SERVICE_ACCOUNT="${SERVICE_ACCOUNT}-read"
READ_ROLE="${ROLE_NAME}.read"
vault-create-k8s-role "${REPLACE_ARG[@]}" "${READ_ROLE}" "${NAMESPACE}/${READ_SERVICE_ACCOUNT}" || exit ${?}

READ_GROUP="${GROUP_NAME}:read"
vault-create-entity "${REPLACE_ARG[@]}" "${READ_ROLE}" "${MNT_K8S}/${READ_ROLE}" || exit ${?}
vault-create-group "${REPLACE_ARG[@]}" --policies "${READ_POLICY}" "${READ_GROUP}" "entity/${READ_ROLE}" "group/${ADMIN_GROUP}" || exit ${?}

vault-create-kv-secret "${REPLACE_ARG[@]}" --mount "${MNT_KV}" "${APP_PATH}" "${SECRET_CONTENT[@]}" || exit ${?}

# All is well!
exit 0
