#!/bin/bash
set -euo pipefail
. /.functions

define_base_vars

. "${__BASEDIR}/.vault-common"

set_or_default UNSEAL_KEYS_DIR "/vault-unseal.d"

#
# List the pods!
#
CMD=(
	kubectl
		get pods
		--namespace "${VAULT_NAMESPACE}"
		--no-headers
		--output=custom-columns="NAME:.metadata.name"
)
[ -n "${VAULT_SELECTOR:-}" ] && CMD+=( --selector="${VAULT_SELECTOR}" )
eyes "Searching for the Vault pods (selector = [${VAULT_SELECTOR}]) in the ${VAULT_NAMESPACE} namespace..."
PODS="$("${CMD[@]}" 2>&1)" || fail "Failed to query the Vault pods (rc=${?}): ${PODS}"

readarray -t POD_LIST < <(echo "${PODS}" | sed -e '/^\s*$/d' | sort -u)
[ ${#POD_LIST[@]} -gt 0 ] || fail "No pods found for Vault using the selector [${VAULT_SELECTOR}]"

say "🔓 Unsealing the Vault pods: [ ${POD_LIST[@]} ]"
FAILED=()
for POD in "${POD_LIST[@]}" ; do
	export VAULT_ADDR="${VAULT_SCHEME}://${POD}.${VAULT_SERVICE}-internal.${VAULT_NAMESPACE}.svc:${VAULT_PORT}"

	RC=0
	eyes "Unsealing ${POD} ..."
	OUT="$(vault status 2>&1)" || RC=${?}
	case ${RC} in
		0 ) ok "\tVault is already unsealed." ; continue ;;
		2 ) err "\tVault is still sealed." ;;
		* ) err "\tError checking vault status (rc=${RC}):\n${OUT}" ; FAILED+=( "${POD}" ) ; continue ;;
	esac

	doing "Vault is sealed on ${POD}, proceeding with unseal..."
	while read KEY_FILE ; do
		KEY="$(<"${KEY_FILE}")"
		OUT="$(vault operator unseal "${KEY}" 2>&1)" && continue
		err "\tERROR: failed to unseal the vault at ${POD} with the key [${KEY_FILE}] (rc=${?}):\n${OUT}"
	done < <(find -L "${UNSEAL_KEYS_DIR}" -mindepth 1 -maxdepth 1 -type f -name "unseal-key-*" | sort)

	RC=0
	OUT="$(vault status 2>&1)" || RC=${?}
	case ${RC} in
		0 ) ok "\tVault unseal successful." ;;
		2 ) err "\tVault is still sealed." ; FAILED+=( "${POD}" ) ;;
		* ) err "\tError checking vault status (rc=${RC}):\n${OUT}" ; FAILED+=( "${POD}" ) ; continue ;;
	esac
done

[ ${#FAILED[@]} -eq 0 ] && ok "Vault unseal is complete!" && exit 0
fail "Could not unseal the following pods: [ ${FAILED[@]} ]"
